# Generated by Django 5.0.1 on 2024-03-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_donateform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
                ('user_contact', models.CharField(max_length=20)),
                ('user_address', models.CharField(max_length=20)),
                ('user_photo', models.FileField(upload_to='user/')),
                ('user_gender', models.CharField(max_length=20)),
                ('user_bloodgroup', models.CharField(max_length=20)),
                ('user_DOB', models.CharField(max_length=20)),
                ('user_hospital', models.CharField(max_length=20)),
            ],
        ),
    ]
