# Generated by Django 5.0.1 on 2024-03-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donateform_name', models.CharField(max_length=20)),
                ('donateform_email', models.CharField(max_length=20)),
                ('donateform_contact', models.CharField(max_length=20)),
                ('donateform_address', models.CharField(max_length=20)),
                ('donateform_photo', models.FileField(upload_to='donateform/')),
                ('donateform_gender', models.CharField(max_length=20)),
                ('donateform_bloodgroup', models.CharField(max_length=20)),
                ('donateform_DOB', models.CharField(max_length=20)),
                ('donateform_hospital', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_donateform',
        ),
    ]
