# Generated by Django 4.2.7 on 2024-03-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_delete_tbl_organs_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_donateform',
        ),
    ]
