# Generated by Django 4.2.7 on 2024-03-20 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_notification'),
        ('Guest', '0009_alter_tbl_hospital_hospital_logo_and_more'),
        ('User', '0006_delete_tbl_donateform'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_donateform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donateform_gender', models.CharField(max_length=20)),
                ('donateform_DOB', models.CharField(max_length=20)),
                ('bloodgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_bloodgroup')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
