# Generated by Django 4.2.7 on 2024-03-21 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_notification'),
        ('User', '0007_tbl_donateform'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_donatingorgan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_status', models.CharField(default=0, max_length=10)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_donateform')),
                ('organs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_organ')),
            ],
        ),
    ]
