# Generated by Django 4.2.7 on 2024-03-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_tbl_nominee_donor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_patient',
        ),
    ]
