# Generated by Django 4.2.7 on 2024-03-22 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_notification'),
        ('Guest', '0009_alter_tbl_hospital_hospital_logo_and_more'),
        ('User', '0010_delete_tbl_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_gender', models.CharField(max_length=20)),
                ('patient_DOB', models.CharField(max_length=20)),
                ('patient_consultinghospital', models.CharField(max_length=20)),
                ('organdata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_organ')),
                ('patient_bloodgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_bloodgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
