# Generated by Django 4.2.7 on 2024-03-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_tbl_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_donateform',
            name='donateform_status',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
