# Generated by Django 4.2.7 on 2024-03-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_tbl_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
