# Generated by Django 5.0.1 on 2024-04-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_alter_tbl_hospital_hospital_logo_and_more'),
        ('User', '0018_rename_tbl_complaint_tbl_complaints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_feedback',
            new_name='tbl_feedbacks',
        ),
    ]
